<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function findAllByArray(Array $array)
	{
		if (empty($array)) {
			return null;
		}
		
		$query = $this->createQueryBuilder('c');
        
		$query->select();
        
		foreach ($array as $key => $element) {
			$query->orWhere("c.id = $element");
		}
		
		$query = $query->getQuery();
		return $query->getResult();
	}
}
