<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }
	
	public function findAllbyArray(Array $array)
	{
		if (empty($array)) {
			return null;
		}
		
		$query = $this->createQueryBuilder('u');
        
		$query->select('u.id, u.username, u.realName, u.avatar');
        
		foreach ($array as $key => $element) {
			$query->orWhere("u.id = $element");
		}
		
		$query = $query->getQuery();
		return $query->getResult();
	}
}
