# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
services:
    app.uploader:
        class: AppBundle\Library\Uploader
        arguments: ['%profile_av_dir%']